---
title: "GEO 712 Repository"
output: github_document
---

# About This Repository

This repository was created for GEOG 712. It contains activities completed for the course, including examples of Markdown and information about my research interests.

# Research Interest

My research interest is **tree-level biomass estimation** using [*remote sensing*](https://en.wikipedia.org/wiki/Remote_sensing). I am interested in using LiDAR, RGB imagery, and machine learning to estimate the biomass of individual urban trees.

# Favourites

## Favourite Music

1.  Every Teardrop Is a Waterfall - Coldplay
2.  Liberian Girl - Michael Jackson
3.  Across the Universe - The Beatles
4.  Welcome to Paradise - Green Day
5.  Godlight - Noah Kahan

## Favourite Equation

$$
a^2+b^2=c^2
$$

## Favourite Artists

| Name | Achievements |
|------------------------------------|------------------------------------|
| The Beatles | The best-selling artists of all time, with 19 No. 1 albums |
| Michael Jackson | His album "Thriller" is the best-selling album of all time |
| Coldplay | One of the world’s most successful modern rock bands |
| Beabadoobee | Her album "This Is How Tomorrow Moves" reached No. 1 on the UK Albums Chart |
| Frank Sinatra | One of the most celebrated vocalists of the 20th century |

# A Chunk of Code

```{r}
print("Hello, World")
```
